### ISSUE TITLE
Modal one closes when its state changes

### ISSUE THREAD

**Issue by patrick-steele-idem** [ianvonholt/marko-widget-test#1]
I'll open an issue for each problem that I find and send a PR with a fix. Below is an explanation for the cause:

Currently, you are using the following code to show the modal dialog:

```javascript
Pubsub.on('showModalOne', function(arg) {
  modal.show();
});
```

This results in the internal state being changed for the nested modal, but the state for the current component is not changed.

In addition, when the button is clicked you are using the following code to update the view:

```javascript
changeStateButton.addEventListener('click', function(e){
  self.setState('loginError', 'State Change Login Error');
  // console.log('State Change One', self.state);
});
```

This results in the state being changed for the outer component, and this results in the outer component and the nested `<modal>` being rerendered. When the nested `<modal>` rerenders it is getting new state based on the input attributes that are provided:

```xml
<modal width="550px" class="component-two" w-id="component-modal-one">
```

NOTE: The `visible` attribute is not being provided so it is defaulting to `false`. As a result, the dialog is being hidden when the button is clicked. I will submit a PR with a simple fix.

**Comment by ianvonholt** [comment]
While this does stop the modal from being closed when the state changes, there is another problem that presents itself. You can't open the modal back up once it is closed. 

The modal is opened by setting the state in the parent. The child widget then does not set the parent state when the window is closed.

**Comment by ianvonholt** [comment]
Issue was solved with using basic events to change values from the child widget.
